### ISSUE TITLE
loading Screen

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-project#11]
## Value proposition

as a user,
i want to see a loading indicator during loading of my data
so that I get a visual feedback of the loading process.

## Description

![image](https://user-images.githubusercontent.com/77203530/181904119-a370079f-de8f-4a51-8c31-2674571e238f.png)

## Acceptance criteria

- [x] A text with loading
- [x] a circle that turns animatedly in a circle

## Tasks

- [x] create a component Loading

**Comment by actyvystom** [comment]
Hi Tomas,
a nice one! I especially like the size of it as it is easy to understand and has a precise scope. 
Just one comment, I suggest using a a cleaner value proposition:  

_as a user,
i want to see a loading indicator during loading of my data
so that I get a visual feedback of the loading process._

But be aware that this would also imply further acceptance criteria and tasks - reflect what happens when the loading process fails...
