### ISSUE TITLE
resources overview

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-project#2]
## Value Proposition

**As a** user
**I need** a resource overview
**to be able to** get a overview of my production.

## Description

![image](https://user-images.githubusercontent.com/77203530/179729771-e09eeda8-1ab5-49dd-bb90-5bb7caef75a7.png)

## Acceptance criteria

- [x] There are five resources: money, iron, fuel, gold, energy.
- [x] The different resources have the starting values
- [ ] Money and Iron have a standard production.
  - [ ] Money : 20/h
  - [x] Iron : 10/h
- [x] The resources are refreshed every seconds.

## Tasks

(for developers team)

- [x] Create components/Ressource(Overview)Bar

**Comment by chris-yooo** [comment]
looks good to me
