### ISSUE TITLE
close anywhere

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-project#22]
## Value proposition

**As a** user
**I want to** click on my screen outside the navigation or tooltip
**to be able** to close the navigation or tooltip.

## Description

![image](https://user-images.githubusercontent.com/77203530/183976712-a174165d-9255-4c7e-bf34-c219021f4d2f.png)

## Acceptance criteria

- [x] Click on the screen outside the navigation to make the navigation disappear to the left.
- [x] Click on the screen outside the tooltip to close the tooltip

## Tasks

- [x] create ref focus event to close the elements
