### ISSUE TITLE
first building

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-project#3]
## Value Proposition

**Als** user
**brauche ich** ein Gebäude
**um** vorhandene Ressourcen auszugeben und Produktion Ressourcen zu steigern

## Description

![image](https://user-images.githubusercontent.com/77203530/179762428-b372cbae-b3e7-4275-9aab-5dfe1c67d4c5.png)

## Acceptance Criteria

- [x] Eine Gebäude Name mit aktueller Gebäude Stufe
- [x] Eine kleine Gebäude Beschreibung
- [x] Ein Zeit Intervall der anzeigt wie lange etwas gebaut wird
- [x] Ressourcen die zur Standard Produktion addiert werden 
- [x] Ressourcen die für den Ausbau des Gebäude abgezogen werden
- [x] Ein Button zum Bauen/Upgraden des Gebäudes
- [x] Im Bauvorgang kann kein weiteres Gebäude gebaut werden

## Tasks

(for developers team)

- [x] Erstelle components/Building

**Comment by chris-yooo** [comment]
looks good to me
