### ISSUE TITLE
main resources buildings

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-project#4]
## Value Proposition

**Als** user
**brauche ich** die Haupt Ressourcen Produktion Gebäude
**um** eine Produktion jeglicher Ressourcen bereitzustellen

## Description

![image](https://user-images.githubusercontent.com/77203530/179961619-654a7a3b-5b2e-4efb-99c7-d7a36da65f86.png)

## Acceptance Criteria

- [x] Jedes Upgrade erhöht die Gebäudeproduktion exponentiell / um einen bestimmten Faktor.
- [x] Die Ressourcen Geld, Eisen und Treibstoff können nicht negativ sein
- [x] Nicht genügend Geld / Eisen / Treibstoff , kann ein Gebäude nicht gebaut / geupdated werden.
- [x] Wird ein Gebäude gebaut, kann ein weiteres erst gebaut werden wenn die Bauzeit abgelaufen ist.

## Tasks

(for developers team)

- [x] Erstellen von Statischen Gebäude Daten in die Datenbank (MongoDB)

**Comment by PReichetanz** [comment]
Hi Thomas,

I still like this user story very much! 🎉

💬 Let's discuss some issues which came to my mind while reading:

## Description
- I reconsidered the wireframe again: I think it's better to write down the correct building names instead of "Building Name" on each card. This way, it becomes clear which card is for solar energy, money, etc.
- It would be ideal if you could change this already here, but I think it's fine if you start with the correct names in your next user story.

## Acceptance Criteria
- There are some features not yet touched. You could add something like 
  - "Bei jedem weiterem Upgrade erhöht sich die Gebäudeproduktion exponentiell / um einen bestimmten Faktor."
  - "Wenn es nicht genügend Geld / Eisen gibt, kann ein Gebäude nicht gebaut / geupdated werden."
  - "Die Ressourcen Eisen, Geld und Treibstoff können nicht negativ sein."
  - "Wenn ein Gebäude gebaut wird, dass mehr Energie verbraucht, als verfügbar ist, zeigt die Energieanzeige die entsprechende negative Zahl an."

**Comment by tomsmulski** [comment]
thanks for the feedback, i have changed the content
