### ISSUE TITLE
building navigation

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-project#5]
## Value Proposition

**Als** user
**brauche ich** eine bessere Übersicht der Gebäude
**um** die Gebäude Übersicht Dynamisch darzustellen

## Description

![image](https://user-images.githubusercontent.com/77203530/179981386-5a64dc37-d1fa-4123-9ef3-fecb076d4ec0.png)

## Acceptance Criteria

- [x] Gebäudeliste in eine Scrollbar Navigation (Links/Rechts)
- [x] Gebäudename
- [x] Aktuelle Gebäudestufe
- [x] Aktuell ausgewähltes Gebäude hervorherben
- [x] Nicht baubare Gebäude markiert angezeigt

## Tasks

(for developers team)

- [x] Erstelle components/buildingNavigation
- [x] Erstellte Gebäude Typen aus User Story 3 tomsmulski/capstone-project#4 sind hier Dynamisch Scrollbar

**Comment by chris-yooo** [comment]
Ich habe mir von der ersten User Story bis jetzt alle angeschaut und verstanden was du vorhast.
Das aus user sotry 3 hier die ganzen gebäude dann auftauchen ist mir ebenfalls klar.

Ich würde glatt behaupten das du für den ersten sprint den wir machen genug backlog's hast :)

weiter so !
