### ISSUE TITLE
building manual

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-project#6]
## Value Proposition

**Als** User
**brauche ich** eine erweiterte Beschreibung des Gebäudes
**um** eventuelle Voraussetzung, Gebäude stufen Produktionsfaktor zu begutachten

## Description

![image](https://user-images.githubusercontent.com/77203530/180056563-c3bfda43-4552-473d-8db5-72ae403c19c1.png)

## Acceptance Criteria

- [x] Ein Button für das öffnen des Handbuchs
- [x] Eine Detaillierte Beschreibung des Gebäudes (Text, Stufe, Produktionswert, Differenz)
- [x] Ein Button um das Handbuch zu verlassen/schließen (x)

## Tasks

(for developers team)

- [x] Create components/manual description

**Comment by chris-yooo** [comment]
ok ich sehe du hast nicht die messages function und den nav header genommen ^^

aber ok

->

Das sieht mir nach einem vernümpftigen feature aus.. über die Building names haben wir ja gesprochen und denen nun richtig leben einzuhauchen find ich auch super.

Da deine app ja nun mucho inhalt hat wirst du dich wohl oder übel in den nächsten 1 2 userstorys mit der navigation zwischen der building seite und XXXX beschäftigen müssen und oder mit der header navbar die den message knopf beinhaltet und dir nachrichten schickt bei fertigstellung von gebäuden -> darauf freu ich mich schon :)

frage von mir, da du ja deine "example DB" mit den gebäuden gefüllt hast steckst du die erweiterten Infos über die gebäude dort mit rein? wäre ja sinnvoll denke ich <3


chris_yooo

**Comment by tomsmulski** [comment]
`frage von mir, da du ja deine "example DB" mit den gebäuden gefüllt hast steckst du die erweiterten Infos über die gebäude dort mit rein? wäre ja sinnvoll denke ich <3`

Ja genau, das kommt mit zu den jeweiligen Gebäude
