### ISSUE TITLE
global technology manuel & side Navigation

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-project#7]
## Value proposition

**As a** user,
**I want to** have one place for all manuals 
**to be able** get quick information about all parts of the game.

## Description

![image](https://user-images.githubusercontent.com/77203530/181257445-627b70a0-615c-4a8c-bc2b-23f0ecb78a64.png)

## Acceptance criteria

- [x] Header navigation with menu
- [x] Menu to open side navigation overlay on left screen 
- [x] Button to close the side navigation
- [x] Button to open the page "Manuel Overview"
- [x] Title for Manuel/s
- [x] Buttons with the categories
- [x] Buttons with all the buildings

## Tasks

- [x] Create components/header with menubar
- [x] Create components/sidenav 
- [x] Create component/side navi button
- [x] Create componen/manuel menu

**Comment by chris-yooo** [comment]
i dond't know man paul says in further USs that a navigation bar are no feature so you can't took this in a USS...

well you were allowed to write your USs in german :D maybe that is allowed with you :P

i think you can put your issue #8 here too

**Comment by tomsmulski** [comment]
> i dond't know man paul says in further USs that a navigation bar are no feature so you can't took this in a USS...
> 
> well you were allowed to write your USs in german :D maybe that is allowed with you :P
> 
> i think you can put your issue #8 here too

@chris-yooo 
yes, thats right, the side navigation do nothing in this moment. it continue with the next user story.
i thought this was too much for one user story, so i split it

**Comment by PReichetanz** [comment]
Hi Thomas,

a good user story! 🎉

💬 Let's discuss some further issues which came to my mind while reading:

## Value Proposition
You can be a little bit more precise here:
- "...**I want** to have one place for all manuals **to be able** get quick information about all parts of the game.

## Description
- Clicking the red navigation button (first picture, left) should open the navigation with the "Manual" link (second picture, left frame). You don't need the right frame of the first picture here.
- I would add what happens if I click, for example, the "Windpower Plant" button in the Building Manual => the detailed information about this building, which you have already implemented, are displayed.

## Acceptance Criteria
- I don't understand what "Title for visual navigation" means, is it the "Manuals" title (second picture, middle frame)? If so, better be clear: The general overview page of all manuals has the state "Manuals" or similar.
