### ISSUE TITLE
tooltip popup hour production 

### ISSUE THREAD

**Issue by tomsmulski** [tomsmulski/capstone-project#8]
## Value proposition

As User,
I see a tooltip
to be able to shows me my current hours production

## Description

![image](https://user-images.githubusercontent.com/77203530/182547879-d484c66f-b30a-4146-8f71-523309121f11.png)

## Acceptance criteria

- [x] click on the resource
- [x] A tooltip popup showing the current hours of production

## Tasks

- [x] Create Component Resources Production Tooltip

**Comment by chris-yooo** [comment]
described in #7

**Comment by chris-yooo** [comment]
As User,
I see a tooltip
to be able to shows me my current hours production

i think this is a good US not to big not to small and for you easy to implement

**Comment by Mitrovic-Milan** [comment]
I think Chris is right
